var dir_aa4bec4954f723cc9ce1e1a5461bbd77 =
[
    [ "BatchPrefs.h", "_batch_prefs_8h_source.html", null ],
    [ "DevicePrefs.h", "_device_prefs_8h_source.html", null ],
    [ "DirectoriesPrefs.h", "_directories_prefs_8h_source.html", null ],
    [ "EffectsPrefs.h", "_effects_prefs_8h_source.html", null ],
    [ "ExtImportPrefs.h", "_ext_import_prefs_8h_source.html", null ],
    [ "GUIPrefs.h", "_g_u_i_prefs_8h_source.html", null ],
    [ "GUISettings.h", "_g_u_i_settings_8h_source.html", null ],
    [ "ImportExportPrefs.h", "_import_export_prefs_8h_source.html", null ],
    [ "KeyConfigPrefs.h", "_key_config_prefs_8h_source.html", null ],
    [ "LibraryPrefs.h", "_library_prefs_8h_source.html", null ],
    [ "MidiIOPrefs.h", "_midi_i_o_prefs_8h_source.html", null ],
    [ "ModulePrefs.h", "_module_prefs_8h_source.html", null ],
    [ "MousePrefs.h", "_mouse_prefs_8h_source.html", null ],
    [ "PlaybackPrefs.h", "_playback_prefs_8h_source.html", null ],
    [ "PrefsDialog.h", "_prefs_dialog_8h_source.html", null ],
    [ "PrefsPanel.h", "_prefs_panel_8h_source.html", null ],
    [ "ProjectsPrefs.h", "_projects_prefs_8h_source.html", null ],
    [ "QualityPrefs.h", "_quality_prefs_8h_source.html", null ],
    [ "RecordingPrefs.h", "_recording_prefs_8h_source.html", null ],
    [ "SpectrogramSettings.h", "_spectrogram_settings_8h_source.html", null ],
    [ "SpectrumPrefs.h", "_spectrum_prefs_8h_source.html", null ],
    [ "ThemePrefs.h", "_theme_prefs_8h_source.html", null ],
    [ "TracksBehaviorsPrefs.h", "_tracks_behaviors_prefs_8h_source.html", null ],
    [ "TracksPrefs.h", "_tracks_prefs_8h_source.html", null ],
    [ "WarningsPrefs.h", "_warnings_prefs_8h_source.html", null ],
    [ "WaveformPrefs.h", "_waveform_prefs_8h_source.html", null ],
    [ "WaveformSettings.h", "_waveform_settings_8h_source.html", null ]
];