var dir_5e80d29b61c444378a543be4dd1414df =
[
    [ "AppCommandEvent.cpp", "_app_command_event_8cpp.html", null ],
    [ "AppCommandEvent.h", "_app_command_event_8h.html", "_app_command_event_8h" ],
    [ "AudacityCommand.h", "_audacity_command_8h_source.html", null ],
    [ "BatchEvalCommand.cpp", "_batch_eval_command_8cpp.html", null ],
    [ "BatchEvalCommand.h", "_batch_eval_command_8h_source.html", null ],
    [ "Command.cpp", "_command_8cpp.html", null ],
    [ "Command.h", "_command_8h.html", "_command_8h" ],
    [ "CommandBuilder.cpp", "_command_builder_8cpp.html", null ],
    [ "CommandBuilder.h", "_command_builder_8h.html", "_command_builder_8h" ],
    [ "CommandContext.cpp", "_command_context_8cpp.html", null ],
    [ "CommandContext.h", "_command_context_8h_source.html", null ],
    [ "CommandDirectory.cpp", "_command_directory_8cpp.html", null ],
    [ "CommandDirectory.h", "_command_directory_8h.html", [
      [ "CommandDirectory", "class_command_directory.html", "class_command_directory" ]
    ] ],
    [ "CommandFlag.h", "_command_flag_8h_source.html", null ],
    [ "CommandFunctors.h", "_command_functors_8h_source.html", null ],
    [ "CommandHandler.cpp", "_command_handler_8cpp.html", null ],
    [ "CommandHandler.h", "_command_handler_8h.html", [
      [ "CommandHandler", "class_command_handler.html", "class_command_handler" ]
    ] ],
    [ "CommandManager.h", "_command_manager_8h_source.html", null ],
    [ "CommandMisc.h", "_command_misc_8h_source.html", null ],
    [ "CommandSignature.cpp", "_command_signature_8cpp.html", null ],
    [ "CommandSignature.h", "_command_signature_8h.html", [
      [ "CommandSignature", "class_command_signature.html", "class_command_signature" ]
    ] ],
    [ "CommandTargets.cpp", "_command_targets_8cpp.html", [
      [ "LongMessageDialog", "class_long_message_dialog.html", "class_long_message_dialog" ],
      [ "MessageDialogTarget", "class_message_dialog_target.html", "class_message_dialog_target" ],
      [ "ExtTargetFactory", "class_ext_target_factory.html", null ]
    ] ],
    [ "CommandTargets.h", "_command_targets_8h_source.html", null ],
    [ "CommandType.cpp", "_command_type_8cpp.html", null ],
    [ "CommandType.h", "_command_type_8h.html", "_command_type_8h" ],
    [ "CompareAudioCommand.cpp", "_compare_audio_command_8cpp.html", "_compare_audio_command_8cpp" ],
    [ "CompareAudioCommand.h", "_compare_audio_command_8h.html", "_compare_audio_command_8h" ],
    [ "Demo.h", "_demo_8h_source.html", null ],
    [ "DragCommand.cpp", "_drag_command_8cpp.html", "_drag_command_8cpp" ],
    [ "DragCommand.h", "_drag_command_8h.html", "_drag_command_8h" ],
    [ "GetInfoCommand.cpp", "_get_info_command_8cpp.html", "_get_info_command_8cpp" ],
    [ "GetInfoCommand.h", "_get_info_command_8h.html", "_get_info_command_8h" ],
    [ "GetTrackInfoCommand.cpp", "_get_track_info_command_8cpp.html", "_get_track_info_command_8cpp" ],
    [ "GetTrackInfoCommand.h", "_get_track_info_command_8h.html", "_get_track_info_command_8h" ],
    [ "HelpCommand.cpp", "_help_command_8cpp.html", null ],
    [ "HelpCommand.h", "_help_command_8h_source.html", null ],
    [ "ImportExportCommands.cpp", "_import_export_commands_8cpp.html", null ],
    [ "ImportExportCommands.h", "_import_export_commands_8h_source.html", null ],
    [ "Keyboard.h", "_keyboard_8h_source.html", null ],
    [ "LoadCommands.h", "_load_commands_8h_source.html", null ],
    [ "MessageCommand.cpp", "_message_command_8cpp.html", null ],
    [ "MessageCommand.h", "_message_command_8h.html", "_message_command_8h" ],
    [ "OpenSaveCommands.cpp", "_open_save_commands_8cpp.html", null ],
    [ "OpenSaveCommands.h", "_open_save_commands_8h_source.html", null ],
    [ "PreferenceCommands.cpp", "_preference_commands_8cpp.html", null ],
    [ "PreferenceCommands.h", "_preference_commands_8h_source.html", null ],
    [ "ResponseQueue.cpp", "_response_queue_8cpp.html", null ],
    [ "ResponseQueue.h", "_response_queue_8h.html", [
      [ "Response", "class_response.html", "class_response" ],
      [ "ResponseQueue", "class_response_queue.html", "class_response_queue" ]
    ] ],
    [ "ScreenshotCommand.h", "_screenshot_command_8h_source.html", null ],
    [ "ScriptCommandRelay.cpp", "_script_command_relay_8cpp.html", "_script_command_relay_8cpp" ],
    [ "ScriptCommandRelay.h", "_script_command_relay_8h.html", "_script_command_relay_8h" ],
    [ "SelectCommand.cpp", "_select_command_8cpp.html", "_select_command_8cpp" ],
    [ "SelectCommand.h", "_select_command_8h.html", "_select_command_8h" ],
    [ "SetClipCommand.cpp", "_set_clip_command_8cpp.html", "_set_clip_command_8cpp" ],
    [ "SetClipCommand.h", "_set_clip_command_8h.html", "_set_clip_command_8h" ],
    [ "SetEnvelopeCommand.cpp", "_set_envelope_command_8cpp.html", null ],
    [ "SetEnvelopeCommand.h", "_set_envelope_command_8h.html", "_set_envelope_command_8h" ],
    [ "SetLabelCommand.cpp", "_set_label_command_8cpp.html", null ],
    [ "SetLabelCommand.h", "_set_label_command_8h.html", "_set_label_command_8h" ],
    [ "SetProjectCommand.cpp", "_set_project_command_8cpp.html", null ],
    [ "SetProjectCommand.h", "_set_project_command_8h.html", "_set_project_command_8h" ],
    [ "SetTrackInfoCommand.h", "_set_track_info_command_8h_source.html", null ],
    [ "Validators.h", "_validators_8h.html", [
      [ "Validator", "class_validator.html", "class_validator" ],
      [ "DefaultValidator", "class_default_validator.html", "class_default_validator" ],
      [ "OptionValidator", "class_option_validator.html", "class_option_validator" ],
      [ "BoolValidator", "class_bool_validator.html", "class_bool_validator" ],
      [ "BoolArrayValidator", "class_bool_array_validator.html", "class_bool_array_validator" ],
      [ "DoubleValidator", "class_double_validator.html", "class_double_validator" ],
      [ "RangeValidator", "class_range_validator.html", "class_range_validator" ],
      [ "IntValidator", "class_int_validator.html", "class_int_validator" ]
    ] ]
];